import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronRight, ChevronLeft } from 'lucide-react';
export const BookingWizard = ({ steps, currentStep, onNext, onPrev, children, isLoading = false, canContinue = true, }) => {
    const isFirstStep = currentStep === 0;
    const isLastStep = currentStep === steps.length - 1;
    return (_jsx("div", { className: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-8 px-4", children: _jsxs("div", { className: "max-w-2xl mx-auto", children: [_jsx("div", { className: "mb-8", children: _jsx("div", { className: "flex justify-between items-center mb-4", children: steps.map((step, index) => (_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: `w-10 h-10 rounded-full flex items-center justify-center font-semibold transition-colors ${index <= currentStep
                                                ? 'bg-blue-600 text-white'
                                                : 'bg-gray-300 text-gray-600'}`, children: index + 1 }), index < steps.length - 1 && (_jsx("div", { className: `flex-1 h-1 mx-2 transition-colors ${index < currentStep ? 'bg-blue-600' : 'bg-gray-300'}` }))] }), _jsx("p", { className: `text-sm font-medium mt-2 ${index <= currentStep ? 'text-blue-600' : 'text-gray-600'}`, children: step.title })] }, step.id))) }) }), _jsxs("div", { className: "bg-white rounded-lg shadow-xl p-8", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h2", { className: "text-2xl font-bold text-gray-900", children: steps[currentStep].title }), _jsx("p", { className: "text-gray-600 mt-2", children: steps[currentStep].description })] }), _jsx("div", { className: "mb-8", children: children }), _jsxs("div", { className: "flex justify-between pt-6 border-t", children: [_jsxs("button", { onClick: onPrev, disabled: isFirstStep || isLoading, className: "flex items-center space-x-2 px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors", children: [_jsx(ChevronLeft, { size: 20 }), _jsx("span", { children: "Previous" })] }), !isLastStep ? (_jsxs("button", { onClick: onNext, disabled: !canContinue || isLoading, className: "flex items-center space-x-2 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors", children: [_jsx("span", { children: isLoading ? 'Loading...' : 'Next' }), _jsx(ChevronRight, { size: 20 })] })) : (_jsx("button", { disabled: !canContinue || isLoading, type: "button", onClick: onNext, className: "px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium", children: isLoading ? 'Booking...' : 'Complete Booking' }))] })] })] }) }));
};
export default BookingWizard;
//# sourceMappingURL=BookingWizard.js.map